---
title: "Agrupamiento-Universidades"
author: "Brayan Ortiz, Juan Peña, Thalea Hesse, Juan Falcon, Daniel Espinal"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(convertr)
library(dplyr)
library(stringr)
```


#Lectura de datos

```{r}
datos <- read.csv("datos/CollegeScorecard.csv")
```

#Limpieza de la BD

```{r}
# Reemplazar algunos valores con NA
df <- replace(datos, datos=="PrivacySuppressed", NA)
df <- replace(df, df==" ", NA)
df <- replace(df, df=="", NA)

# Se borran columnas con valores nulos (>20%)
df <- df[,-which(colMeans(is.na(df)) >= 0.2)]

# Se borran filas con valores nulos
# delete.na <- function(df, n=0) {
#  df[rowSums(is.na(df)) <= n,]
# }
# df <- delete.na(df)

#Eliminar columnas manualmente
df <- subset(df, select = -c(INSTNM, NPCURL, INSTURL))
```

# Convertir los tipos de datos
```{r}
columnas <- data.frame(colnames(df))

columnas_CIP <- columnas %>% 
  filter(str_detect(colnames.df., "^CIP"))

df <- df %>% 
  mutate_at(vars(main, region, CURROPER), list(as.factor)) %>% 
  mutate_at(vars(columnas_CIP$colnames.df.), list(as.factor))
```

```{r}
#Separar df por tipo de columna
# colSums(is.na(df)/7804)
df_fact <- df[sapply(df, is.factor)]
df <- df %>% mutate(across(.cols=where(is.character), .fns=as.factor))
df_num <- df[sapply(df, is.numeric)]
```



# Modelo

```{r}

```

